version: "3.9"

services:
  bookmarks_service:
    container_name: bookmarks_service
    build: .
    env_file:
      - .env
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      - bookmarks_service_network
    depends_on:
      bookmarks_service_db:
        condition: service_healthy

  bookmarks_service_db:
    container_name: bookmarks_service_db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s
    volumes:
      - bookmarks_db_volume:/var/lib/postgresql/data
    ports:
      - "5632:5432"
    networks:
      - bookmarks_service_network

volumes:
  bookmarks_db_volume:
    name: bookmarks_db_volume

networks:
  bookmarks_service_network:
    name: bookmarks_service_network
